use lua5.4 by default
there is a lua5.5 in arch now, but in 64 bits only, making the 32 bit
link output an error about undefined reference to luaL_openselectedlibs.
So the best is to ask explicitely for lua5.4, I don't need 5.5 for now
anyway.